title: Pratik Pawar
logo: docs/assets/Headshot.png
description: Data Analyst | Businesss Intelligence | Expert in SQL, Python, PowerBI, Tableau, MS Excel, Azure, AWS, GCP
#show_downloads: true
theme: jekyll-theme-minimal
